name: backend_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

dependencies:
  home_assistant_ws:
    path: ../home_assistant_ws
  dart_common:
    path: ../dart_common
  uuid: ^4.0.0
  path: ^1.8.0
  collection: ^1.18.0
  crypto: ^3.0.3
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.0
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
